import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { ChatMessage } from '@/lib/chatParser';

// Register fonts if needed, but standard PDF fonts (Times-Roman) work out of the box for serif.

const styles = StyleSheet.create({
    page: {
        paddingTop: 50,
        paddingBottom: 50,
        paddingLeft: 60,
        paddingRight: 60,
        fontFamily: 'Times-Roman',
        backgroundColor: '#ffffff',
    },
    coverPage: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    coverTitle: {
        fontSize: 42,
        marginBottom: 20,
        textAlign: 'center',
        fontFamily: 'Times-Roman',
        fontWeight: 'bold',
        color: '#1a1a1a',
    },
    coverSubtitle: {
        fontSize: 20,
        color: '#555555',
        marginBottom: 60,
        fontStyle: 'italic',
    },
    coverMeta: {
        fontSize: 10,
        color: '#888888',
        marginTop: 'auto',
        marginBottom: 20,
        fontFamily: 'Times-Roman',
    },
    chapterContainer: {
        marginBottom: 20,
    },
    chapterTitle: {
        fontSize: 28,
        fontFamily: 'Times-Roman',
        fontWeight: 'bold',
        textAlign: 'center',
        marginTop: 60,
        marginBottom: 40,
        paddingBottom: 15,
        borderBottomWidth: 0.5,
        borderBottomColor: '#cccccc',
        color: '#1a1a1a',
    },
    dateHeader: {
        fontSize: 11,
        color: '#666666',
        textAlign: 'center',
        marginTop: 25,
        marginBottom: 15,
        fontStyle: 'italic',
        fontFamily: 'Times-Roman',
    },
    messageRow: {
        marginBottom: 12,
        flexDirection: 'row',
        flexWrap: 'wrap',
        lineHeight: 1.6,
    },
    sender: {
        fontSize: 11,
        fontFamily: 'Times-Roman',
        fontWeight: 'bold',
        marginRight: 6,
        color: '#2d2d2d',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    content: {
        fontSize: 12,
        color: '#333333',
        fontFamily: 'Times-Roman',
    },
    timestamp: {
        fontSize: 8,
        color: '#bbbbbb',
        marginLeft: 6,
    },
    footer: {
        position: 'absolute',
        bottom: 20,
        left: 0,
        right: 0,
        textAlign: 'center',
        fontSize: 9,
        color: '#dddddd',
        fontFamily: 'Times-Roman',
    },
});

interface DigitalBookPDFProps {
    messages: ChatMessage[];
    title: string;
}

export const DigitalBookPDF = ({ messages, title }: DigitalBookPDFProps) => {
    const years = Array.from(new Set(messages.map(m => new Date(m.timestamp).getFullYear()))).sort();
    const startDate = new Date(messages[0].timestamp).toLocaleDateString();
    const endDate = new Date(messages[messages.length - 1].timestamp).toLocaleDateString();

    return (
        <Document>
            {/* Cover Page */}
            <Page size="A4" style={styles.page}>
                <View style={styles.coverPage}>
                    <Text style={styles.coverTitle}>{title}</Text>
                    <Text style={styles.coverSubtitle}>A Digital Memory</Text>

                    <Text style={styles.coverMeta}>
                        {startDate} — {endDate}
                    </Text>
                    <Text style={{ fontSize: 10, color: '#cccccc' }}>Generated by WAppify</Text>
                </View>
            </Page>

            {/* Content Pages */}
            <Page size="A4" style={styles.page} wrap>
                <Text style={styles.footer} render={({ pageNumber, totalPages }) => (
                    `${pageNumber} / ${totalPages}`
                )} fixed />

                {years.map((year, yearIndex) => {
                    const yearMessages = messages.filter(m => new Date(m.timestamp).getFullYear() === year);
                    if (yearMessages.length === 0) return null;

                    return (
                        <View key={year} break={yearIndex > 0}>
                            <Text style={styles.chapterTitle}>Chapter {year}</Text>

                            {yearMessages.map((msg, i) => {
                                const date = new Date(msg.timestamp);
                                const prevDate = i > 0 ? new Date(yearMessages[i - 1].timestamp) : null;
                                const showDate = !prevDate || prevDate.getDate() !== date.getDate() || prevDate.getMonth() !== date.getMonth();

                                return (
                                    <View key={i} wrap={false}>
                                        {showDate && (
                                            <Text style={styles.dateHeader}>
                                                — {date.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })} —
                                            </Text>
                                        )}
                                        <View style={styles.messageRow}>
                                            <Text style={styles.sender}>{msg.sender}:</Text>
                                            <Text style={styles.content}>
                                                {msg.content}
                                                <Text style={styles.timestamp}> {date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text>
                                            </Text>
                                        </View>
                                    </View>
                                );
                            })}
                        </View>
                    );
                })}
            </Page>
        </Document>
    );
};
